# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2db5c29b4c3a4bfb956aa3c574e5139cc7daffa1b4e5a4e0f9986b771ccd736cb305b2e8ead3305b04e017328aca7ea0f2eb2544ffd37547d6e478636b5a2c89

test:
  secret_key_base: 8f113312639a1f6d6af1b15d840d13f99c20eedccb9a28ebb6f689152d461ba7bf7ac9096f094ddce7fa53f9947bb434105e7b0910754ab562cab03fdda354b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
